### ISSUE TITLE
How about CDN url?

### ISSUE THREAD

**Issue by darcksday** [frostealth/yii2-aws-s3#15]
How about CDN url?

**Comment by davidjeddy** [comment]
Please clarify. Are you wanting the URI of an S3 resource?

**Comment by frostealth** [comment]
Working with Amazon CloudFront or another CDN isn't the task of this component.
I don't see any reason to add it.

Would you describe your problem?

If you would like to work with Amazon CloudFront, you should use the official [`CloudFronClient`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.CloudFront.CloudFrontClient.html).
Otherwise, you always can concatenate the CDN hostname with a filename like this:

``` php
function cdn_url($pathname)
{
    return Yii::$app->params['cdnHostname'] . '/' . $pathname;
}

$url = cdn_url('path/to/my/s3/object.ext');
```
